/*
 * app_config.h
 *
 *  Created on: 6 Aug 2024
 *      Author: Maldo
 */

#ifndef CONFIG_APP_CONFIG_H_
#define CONFIG_APP_CONFIG_H_

#define APP_CONFIG_DEVICE_MODEL 0

#define APP_CONFIG_FIRMWARE_VERSION_MAJOR 0
#define APP_CONFIG_FIRMWARE_VERSION_MINOR 0
#define APP_CONFIG_FIRMWARE_VERSION_PATCH 1

#define APP_CONFIG_BURNER_DELAY_TIME_MS    2000
#define APP_CONFIG_BURNER_RESET_TIME_MS    3000
#define APP_CONFIG_BURNER_DEBOUNCE_TIME_MS 5000

#endif /* CONFIG_APP_CONFIG_H_ */
