#include "hal_data.h"
#include "bsp/system.h"
#include "bsp/heartbit.h"
#include "bsp/digin.h"
#include "bsp/adc.h"
#include "bsp/rs232.h"
#include "bsp/pwm.h"
#include "bsp/coin_reader.h"
#include "bsp/power_off.h"
#include "model/model.h"
#include "controller/controller.h"


FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************/
/**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This
 * function
 * is called by main() when no RTOS is used.

 * **********************************************************************************************************************/
void hal_entry(void) {
    static mut_model_t model = {0};

    bsp_system_init();
    bsp_digin_init();
    bsp_pwm_init();
    bsp_adc_init();
    bsp_rs232_init();
    bsp_coin_reader_init();
    bsp_power_off_init(controller_power_off, &model);

    controller_init(&model);

    for (;;) {
        controller_manage(&model);

        bsp_heartbit_manage();
        bsp_digin_manage();
        bsp_adc_manage();
        bsp_coin_reader_manage();

        bsp_io_level_t level = BSP_IO_LEVEL_HIGH;
        g_ioport.p_api->pinRead(g_ioport.p_ctrl, BSP_PIN_INT0, &level);
        if (level == BSP_IO_LEVEL_LOW) {
            __NOP();
            __NOP();
            __NOP();
        }

        __WFI();
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************/
/**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event) {
    if (BSP_WARM_START_RESET == event) {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take

         * * more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event) {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&g_ioport_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is
 *
 * not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable() {}
FSP_CPP_FOOTER

#endif
